name: motoboy
description: "Sistema de Motoboy / MototÃ¡xi"
publish_to: 'none'

version: 1.0.22+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # Network / Core
  dio: ^5.8.0+1
  dartz: ^0.10.1
  get_it: ^8.0.3
  intl: ^0.20.2
  meta: ^1.12.0
  uuid: ^4.5.1
  path: ^1.9.0

  # Storage
  shared_preferences: ^2.5.2

  # Localization
  flutter_localizations:
    sdk: flutter

  # State Management
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0

  # UI / Utils
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.12
  flutter_svg: ^2.0.17
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # Enable code generation for l10n
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/svg/
    - assets/audio/
